# ------------------------------------------------------------------------------
# Example of source configuration
#
# [sources.argocd_webhook]
# enabled = true
# transformer_refs = ["argocd_metadata", "argocd_notifications"]

# [sources.argocd_webhook.extractor]
# type = "webhook"
# id = "000-argocd"
# headers_to_keep = []

# [sources.argocd_webhook.extractor.headers]
# # token override by environment variable reads from the secret
# "authorization" = { type = "signature", signature_encoding = "base64", signature_on = "body", signature_prefix = "Bearer ", token = "changeme" }

# the argocd_metadata transformer will add information not available from input events
# the added information will be available in the metadata, then used by following transformers
[transformers.argocd_metadata]
type = "vrl"
template = """
.metadata = object(.metadata) ?? {}

[{
  "metadata": merge(.metadata, {
    "environment_id": .body.context.environment || .body.app.spec.destination.server || "unknown",
  }),
  "headers": .headers,
  "body": .body,
}]
"""

[transformers.argocd_notifications]
type = "vrl"
template_file = "./transformer.vrl"
