[tasks."test"]
description = "run the transformation example argocd_notifications (use `--mode review` to review and update)"
run = """cdviz-collector \
  transform \
  --disable-otel \
  --mode {{option(name="mode", default="check")}} \
  --config ./cdviz-collector.toml \
  -t argocd_metadata,argocd_notifications \
  --input ./inputs \
  --output ./outputs
"""
