monorepo_root = true

[settings]
experimental = true

[monorepo]
config_roots = [
  "argocd_notifications",
  "bitbucket_webhook",
  "cdevents/*",
  "forgejo_webhook",
  "gcp_artifactregistry_rest_api",
  "gcp_artifactregistry_webhook",
  "gcp_cloudbuild_rest_api",
  "gcp_cloudbuild_webhook",
  "gcp_cloudrun_rest_api",
  "gcp_cloudrun_webhook",
  "gitea_webhook",
  "github_events",
  "github_rest_api",
  "gitlab_webhook",
  "jenkins_rest_api",
  "jira_webhook",
  "kubewatch_cloudevents",
  "passthrough",
]

[tools]
"dprint" = "latest"
"github:davidB/json-simple-obfuscator" = "latest"
"github:cdviz-dev/cdviz-collector" = "0.49.0"

[tasks."format"]
alias = "fmt"
depends = [":obfuscate"]
description = "Format the code and sort dependencies"
run = "dprint fmt"

[tasks.obfuscate]
description = "run all 'obfuscate'"
depends = ["//...:obfuscate"]

[tasks."test"]
description = "run all 'test' tasks of sub module"
depends = ["//...:test"]

[tasks."ci"]
depends = [":test"]
run = "cdviz-collector --version"
description = "set of tasks run by CI"
