# ------------------------------------------------------------------------------
# Example of source configuration
#
# [sources.bitbucket_webhook]
# enabled = true
# transformer_refs = ["bitbucket_events"]

# [sources.bitbucket_webhook.extractor]
# type = "webhook"
# id = "000-bitbucket"
# # required: bitbucket has no event type in the body, only in the header
# headers_to_keep = ["x-event-key"]

# [sources.bitbucket_webhook.extractor.headers]
# # token override by environment variable reads from the secret
# "x-hub-signature" = { type = "signature", signature_encoding = "hex", signature_on = "body", signature_prefix = "sha256=", token = "changeme" }

[transformers]
bitbucket_events_0_5 = { type = "vrl", template_file = "./to_v0_5.vrl" }
