[tasks."test"]
description = "run the transformation example passthrough (use `--mode review` to review and update)"
usage = """
flag "--mode <mode>" default="check" help="transform mode: check or review"
"""
run = """cdviz-collector \
  transform \
  --disable-otel \
  --mode ${usage_mode} \
  --config ./cdviz-collector.toml \
  -t passthrough \
  --input ./inputs \
  --output ./inputs
"""
