# ------------------------------------------------------------------------------
# Example of source configuration
#
# [sources.kubewatch_webhook]
# enabled = true
# transformer_refs = [ "log", "kubewatch_metadata", "log", "kubewatch_cloudevents", "log" ]
#
# [sources.kubewatch_webhook.extractor]
# type = "webhook"
# id = "000-kubewatch"

[transformers]
kubewatch_cloudevents_0_4 = { type = "vrl", template_file = "./to_v0_4.vrl" }
kubewatch_cloudevents_0_5 = { type = "vrl", template_file = "./to_v0_5.vrl" }

# the kubewatch_metadata transformer will add information not available from input events
# the added information will be available in the metadata, then used by following transformers
[transformers.kubewatch_metadata]
type = "vrl"
template = """
.metadata = object(.metadata) ?? {}

[{
  "metadata": merge(.metadata, {
    "environment_id": "cluster/A-dev",
  }),
  "headers": .headers,
  "body": .body,
}]
"""
