# ------------------------------------------------------------------------------
# Example of source configuration
#
# [sources.kubewatch_webhook]
# enabled = true
# transformer_refs = [ "log", "kubewatch_metadata", "log", "kubewatch_cloudevents", "log" ]
#
# [sources.kubewatch_webhook.extractor]
# type = "webhook"
# id = "000-kubewatch"

# the kubewatch_metadata transformer will add information not available from input events
# the added information will be available in the metadata, then used by following transformers
[transformers.kubewatch_metadata]
type = "vrl"
template = """
.metadata = object(.metadata) ?? {}

[{
  "metadata": merge(.metadata, {
    "environment_id": "cluster/A-dev",
  }),
  "headers": .headers,
  "body": .body,
}]
"""

[transformers.kubewatch_cloudevents]
type = "vrl"
template_file = "./transformer.vrl"
