# the webhook should be configured

@host = http://localhost:8080
@kubewatch_webhook_path = /webhook/000-kubewatch


###
GET /healthz

?? status == 200

###
POST {{host}}{{kubewatch_webhook_path}}
Content-Type: application/json
x-hub-signature-256: to_process

< ./inputs/deployment/update.json

?? status == 201
