# ------------------------------------------------------------------------------
# Example of source configuration
#
# [sources.github_webhook]
# enabled = true
# transformer_refs = ["github_events"]

# [sources.github_webhook.extractor]
# type = "webhook"
# id = "000-github"
# headers_to_keep = []

# [sources.github_webhook.extractor.headers]
# # token override by environment variable reads from the secret
# "x-hub-signature-256" = { type = "signature", signature_encoding = "hex", signature_on = "body", signature_prefix = "sha256=", token = "changeme" }

[transformers.github_events]
type = "vrl"
template_file = "./transformer.vrl"

# # Configure remote repository
# [remote.transformers-community]
# type = "github"
# owner = "cdviz-dev"
# repo = "transformers-community"
# reference = "main"  # Optional: specify branch, tag, or commit

# # Use remote transformer
# [transformers.github_events]
# type = "vrl"
# template_rfile = "transformers-community:///github_events/transformer.vrl"
